name: first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            
        - name: Checkout repository
          uses: actions/checkout@

        - name: Welcome Message
          run: echo "My first github workflow"

        - name: List Files
          run: ls
        - name: Readme fiels
          run: cat README.md