name: first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: List and Read Files
          run: |
               echo "My first github workflow"
               ls -ltra
               cat README.md 
        - name: Generate ASCII Artworks
          run: cowsay -f Lion "run for a cover..I am a Lion...Roar" >> lion.txt
        
        # - name: List Files
        #   run: ls -a
        # - name: Readme fiels
        #   run: cat README.md