name: Genrate ASCII Artwork

on: 
   push 

jobs:
    ascii_job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Install Cowsay Program
          run: sudo apt install cowsay -y 

        - name: Execute cowsay command
          run: cowsay -f tux "run for a cover..I am a tux...Roar" >> tux.txt

        - name: Test file exists
          run:  grep -i "tux" tux.txt
        - name: read file
          run: cat tux.txt

        - name: List repo files
          run: ls-ltra

