name: Matrix Strategy

on: 
    push:

jobs:
    deploy:
        # concurrency:
        #     group: deploy-${{ github.ref }}
        #     cancel-in-progress: true
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-20.04, windows-latest]
                images: [hello-world, alpine]
                exclude:
                    - images: alpine
                      os: windows-latest
        runs-on: ${{matrix.os}}
        steps:
        - name: Echo Docker info
          run: docker info
        - name: Run Image on ${{matrix.os}}
          run: docker run ${{matrix.images}}