name: Multi-Job-Demo

on:
    push:
    workflow_dispatch:

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay Program
          run: sudo apt install cowsay -y
        
        - name: Execute cowsay CMD
          run: cowsay -f tux "run for a cover..I am a tux...Roar" >> tux.txt
        
        - name: Upload tux file
          uses: actions/upload-artifact@v4
          with:
            name: Tux-file
            path: tux.txt

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps: 
        - name: Download tux file
          uses: actions/download-artifact@v4
          with:
            name: Tux-file

        - name: Test file exists
          run: grep -i "tux" tux.txt

    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        - name: Download tux file
          uses: actions/download-artifact@v4
          with:
            name: Tux-file

        - name: Read the file
          run: cat tux.txt

        - name: Deploy
          run: echo deploying ...
